name: Add ARM64 Architecture
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Add ARM64 Architecture
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
